import type { WorkspaceInput } from "../../application/workspace-reducer";
import type { AutomationDraft, AutomationPatch } from "../../domain/automation";
import type { DiffRange } from "../../domain/diff";
import type { FindResults, FindTarget } from "../../domain/find";
import type { AgentEngine, AgentModel } from "../../domain/agent-engine";
import type { AgentEffort, ExecutionPolicy, SubagentGroup } from "../../domain/run";
import type { SettingsSection } from "../../domain/settings-section";
import type { SidebarMode, SidebarSection } from "../../domain/sidebar";
import type { RunAttachment, TaskDropTarget } from "../../domain/task";
import type { ThemeMode } from "../../domain/theme";
import type { ReviewTarget } from "../../domain/review";
import { systemPrefersDark } from "../theme";

/** The named shorthands the UI reaches for, each one a single command through the same door. */
export function workspaceActions(dispatch: (input: WorkspaceInput) => Promise<void>) {
  return {
    newTask: (projectId?: string, worktreeId?: string) => dispatch({ type: "task.new", ...(projectId ? { projectId } : {}), ...(worktreeId ? { worktreeId } : {}) }),
    openFolder: () => dispatch({ type: "project.open" }),
    selectTask: (taskId: string) => dispatch({ type: "task.select", taskId }),
    archiveTask: (taskId: string) => dispatch({ type: "task.archive", taskId }),
    restoreTask: (taskId: string) => dispatch({ type: "task.restore", taskId }),
    clearArchive: () => dispatch({ type: "task.clear-archive" }),
    renameTask: (taskId: string, title: string) => dispatch({ type: "task.rename", taskId, title }),
    moveTask: (taskId: string, target: TaskDropTarget) => dispatch({ type: "task.move", taskId, target }),
    forkTask: (taskId: string, worktree = false) => dispatch({ type: "task.fork", taskId, ...(worktree ? { worktree } : {}) }),
    toggleProject: (projectId: string) => dispatch({ type: "view.toggle-project", projectId }),
    moveProject: (projectId: string, index: number) => dispatch({ type: "project.move", projectId, index }),
    removeProject: (projectId: string) => dispatch({ type: "project.remove", projectId }),
    editProject: (projectId: string, edit: { name?: string | null; root?: string }) => dispatch({ type: "project.edit", projectId, ...edit }),
    editProjectOpen: (projectId: string) => dispatch({ type: "view.edit-project", projectId }),
    editProjectClose: () => dispatch({ type: "view.edit-project", projectId: null }),
    dismissTask: (taskId: string) => dispatch({ type: "task.dismiss", taskId }),
    dismissAllTasks: () => dispatch({ type: "task.dismiss-all" }),
    setSectionOpen: (section: SidebarSection, open: boolean) => dispatch({ type: "view.set-section-open", section, open }),
    setSubagentGroup: (group: SubagentGroup, open: boolean) => dispatch({ type: "view.set-subagent-group", group, open }),
    setTheme: (theme: string) => dispatch({ type: "view.set-theme", theme }),
    setThemeFamily: (family: string) => dispatch({ type: "view.set-theme-family", family, systemDark: systemPrefersDark() }),
    setThemeMode: (mode: ThemeMode) => dispatch({ type: "view.set-theme-mode", mode, systemDark: systemPrefersDark() }),
    setSystemScheme: (dark: boolean) => dispatch({ type: "view.system-scheme", dark }),
    setUiFont: (font: string) => dispatch({ type: "view.set-ui-font", font }),
    setMonoFont: (font: string) => dispatch({ type: "view.set-mono-font", font }),
    setReadingSize: (size: number) => dispatch({ type: "view.set-reading-size", size }),
    setTerminalSize: (size: number) => dispatch({ type: "view.set-terminal-size", size }),
    setSidebarMode: (mode: SidebarMode) => dispatch({ type: "view.set-sidebar-mode", mode }),
    setSessionPanelOpen: (open: boolean) => dispatch({ type: "view.set-session-panel-open", open }),
    setPlainEnglish: (enabled: boolean) => dispatch({ type: "view.set-plain-english", enabled }),
    setChromeBrowser: (enabled: boolean) => dispatch({ type: "view.set-chrome-browser", enabled }),
    setComputerUse: (enabled: boolean) => dispatch({ type: "view.set-computer-use", enabled }),
    setBrowserTools: (enabled: boolean) => dispatch({ type: "view.set-browser-tools", enabled }),
    setNotifications: (enabled: boolean) => dispatch({ type: "view.set-notifications", enabled }),
    setSidebarOpen: (open: boolean) => dispatch({ type: "view.set-sidebar-open", open }),
    setShortcut: (action: string, binding: string | null) => dispatch({ type: "view.set-shortcut", action, binding }),
    resetShortcuts: () => dispatch({ type: "view.reset-shortcuts" }),
    captureShortcut: (action: string | null) => dispatch({ type: "view.capture-shortcut", action }),
    inspectSubagent: (subagentId: string) => dispatch({ type: "view.inspect-subagent", subagentId }),
    setOpenMenu: (menu: string | null) => dispatch({ type: "view.set-menu", menu }),
    goBack: () => dispatch({ type: "view.go-back" }),
    goForward: () => dispatch({ type: "view.go-forward" }),
    setPrompt: (prompt: string) => dispatch({ type: "view.set-prompt", prompt }),
    setPolicy: (policy: ExecutionPolicy) => dispatch({ type: "task.set-policy", policy }),
    setModel: (engine: AgentEngine, model: AgentModel) => dispatch({ type: "task.set-model", engine, model }),
    setEffort: (engine: AgentEngine, effort: AgentEffort) => dispatch({ type: "task.set-effort", engine, effort }),
    readEngineStatus: () => dispatch({ type: "engine.read" }),
    refreshEngineStatus: () => dispatch({ type: "engine.read", refresh: true }),
    signInEngine: (engine: AgentEngine) => dispatch({ type: "engine.sign-in", engine }),
    setWorktree: (worktree: boolean) => dispatch({ type: "task.set-worktree", worktree }),
    moveWorktree: (worktree: boolean) => dispatch({ type: "view.move-worktree", worktree }),
    moveWorktreeClose: () => dispatch({ type: "view.move-worktree", worktree: null }),
    setBranch: (branch: string | null, create?: boolean) => dispatch({ type: "task.set-branch", branch, ...(create ? { create } : {}) }),
    checkoutBranch: (branch: string, create?: boolean) => dispatch({ type: "task.checkout-branch", branch, ...(create ? { create } : {}) }),
    deleteWorktree: () => dispatch({ type: "worktree.delete" }),
    refreshWorktrees: () => dispatch({ type: "worktree.refresh" }),
    revealWorktree: (root: string) => dispatch({ type: "worktree.reveal", root }),
    deleteManagedWorktree: (root: string) => dispatch({ type: "worktree.delete", root }),
    sendPrompt: (attachments: RunAttachment[] = [], steer = false) => dispatch({ type: "task.send", attachments, ...(steer ? { steer } : {}) }),
    clearGoal: (taskId: string) => dispatch({ type: "task.send", taskId, text: "/goal clear", steer: true }),
    steerQueued: (messageId: string) => dispatch({ type: "task.steer-queued", messageId }),
    dropQueued: (messageId: string) => dispatch({ type: "task.drop-queued", messageId }),
    saveAutomation: (draft: Omit<AutomationDraft, "taskId">) => dispatch({ type: "automation.save", draft }),
    updateAutomation: (patch: AutomationPatch) => dispatch({ type: "automation.update", patch }),
    deleteAutomation: () => dispatch({ type: "automation.delete" }),
    runAutomationNow: () => dispatch({ type: "automation.run-now" }),
    compactContext: () => dispatch({ type: "run.compact" }),
    openReview: () => dispatch({ type: "review.open" }),
    setReviewStep: (step: "targets" | "base" | "commit" | "custom") => dispatch({ type: "review.set-step", step }),
    closeReview: () => dispatch({ type: "review.close" }),
    startReview: (target: ReviewTarget) => dispatch({ type: "review.start", target }),
    cancelRun: () => dispatch({ type: "run.cancel" }),
    stopBackgroundProcess: (processId: string) => dispatch({ type: "run.stop-process", processId }),
    decideApproval: (allow: boolean) => dispatch({ type: "run.decide", allow }),
    dismissComputerUseSetup: () => dispatch({ type: "view.dismiss-computer-use-setup" }),
    setDockOpen: (open: boolean) => dispatch({ type: "view.set-dock-open", open }),
    setDockExpanded: (expanded: boolean) => dispatch({ type: "view.set-dock-expanded", expanded }),
    setSettingsOpen: (open: boolean) => dispatch({ type: "view.set-settings-open", open }),
    openSettingsSection: (section: SettingsSection) => dispatch({ type: "view.set-settings-open", open: true, section }),
    closeTab: () => dispatch({ type: "view.close-tab" }),
    openDockPanel: (panel: string) => dispatch({ type: "view.open-dock-panel", panel }),
    closeDockPanel: (panel: string) => dispatch({ type: "view.close-dock-panel", panel }),
    openWorkflow: (workflowId: string) => dispatch({ type: "view.open-workflow", workflowId }),
    selectDockTab: (tab: string) => dispatch({ type: "view.select-dock-tab", tab }),
    toggleDiff: () => dispatch({ type: "diff.toggle" }),
    refreshDiff: () => dispatch({ type: "diff.refresh" }),
    setDiffRange: (range: DiffRange) => dispatch({ type: "diff.set-range", range }),
    setDiffCollapsed: (path: string, collapsed: boolean) => dispatch({ type: "diff.set-collapsed", path, collapsed }),
    setDiffViewed: (path: string, viewed: boolean) => dispatch({ type: "diff.set-viewed", path, viewed }),
    setDiffSplit: (split: boolean) => dispatch({ type: "diff.set-split", split }),
    setDiffIgnoreWhitespace: (ignore: boolean) => dispatch({ type: "diff.set-ignore-whitespace", ignore }),
    openBrowser: (url: string, newTab = false, tabId?: string) => dispatch({ type: "browser.open", url, ...(newTab ? { newTab } : {}), ...(tabId ? { tabId } : {}) }),
    newBrowserTab: () => dispatch({ type: "browser.new-tab" }),
    selectBrowserTab: (tabId: string) => dispatch({ type: "browser.select-tab", tabId }),
    closeBrowserTab: (tabId: string) => dispatch({ type: "browser.close-tab", tabId }),
    goInBrowser: (delta: -1 | 1, tabId?: string) => dispatch({ type: "browser.go", delta, ...(tabId ? { tabId } : {}) }),
    reloadBrowser: (tabId?: string) => dispatch({ type: "browser.reload", ...(tabId ? { tabId } : {}) }),
    decideBrowser: (allow: boolean) => dispatch({ type: "browser.decide", allow }),
    clearBrowserData: () => dispatch({ type: "browser.clear-data" }),
    openTerminal: () => dispatch({ type: "terminal.open" }),
    openFolderInApp: (appId: string) => dispatch({ type: "app.open-folder", appId }),
    selectTerminal: (terminalId: string) => dispatch({ type: "terminal.select", terminalId }),
    closeTerminal: (terminalId: string) => dispatch({ type: "terminal.close", terminalId }),
    sendToTerminal: (terminalId: string, data: string) => dispatch({ type: "terminal.input", terminalId, data }),
    openJump: () => dispatch({ type: "view.jump-open" }),
    setJumpQuery: (query: string) => dispatch({ type: "view.jump-query", query }),
    stepJump: (delta: -1 | 1) => dispatch({ type: "view.jump-step", delta }),
    chooseJump: (taskId: string) => dispatch({ type: "view.jump-choose", taskId }),
    closeJump: () => dispatch({ type: "view.jump-close" }),
    openFind: () => dispatch({ type: "view.find-open" }),
    setFindQuery: (query: string) => dispatch({ type: "view.find-query", query }),
    stepFind: (delta: -1 | 1) => dispatch({ type: "view.find-step", delta }),
    closeFind: () => dispatch({ type: "view.find-close" }),
    reportFind: (target: FindTarget, results: FindResults) => dispatch({ type: "find.results", target, results }),
    resizeTerminal: (terminalId: string, cols: number, rows: number) => dispatch({ type: "terminal.resize", terminalId, cols, rows }),
    setRemoteEnabled: (enabled: boolean) => dispatch({ type: "remote.set-enabled", enabled }),
    setRemoteLanExposed: (exposed: boolean) => dispatch({ type: "remote.set-lan-exposed", exposed }),
    createRemotePairingCode: () => dispatch({ type: "remote.create-pairing-code" }),
    revokeRemoteDevice: (deviceId: string) => dispatch({ type: "remote.revoke-device", deviceId }),
    setTailscaleServe: (enabled: boolean) => dispatch({ type: "remote.set-tailscale-serve", enabled }),
    refreshRemote: () => dispatch({ type: "remote.refresh" }),
  };
}
