// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backend routing policy. Wire values match the accounts/check contract.
 */
export type AccountRoutingOverride = "NO_CONSTRAINT" | "us" | "us_cr";
