// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkDomainPermission } from "./NetworkDomainPermission";

export type ApplicationNetworkRequirements = {
/**
 * When enabled, only explicitly allowed exact domains may be contacted.
 */
enabled: boolean, domains: { [key in string]?: NetworkDomainPermission }, };
