// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledApp } from "./InstalledApp";

/**
 * The installed connectors in one committed runtime snapshot.
 */
export type AppsInstalledResponse = { apps: Array<InstalledApp>, };
