// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAgentConfigMigrationItem } from "./ExternalAgentConfigMigrationItem";

export type ExternalAgentConfigImportParams = { migrationItems: Array<ExternalAgentConfigMigrationItem>,
/**
 * Optional identifier for the product that initiated the import.
 */
source?: string | null,
/**
 * Opaque provider identifier supplied by the caller for analytics attribution and import
 * history display. This does not select the migration source.
 */
providerId?: string | null,
/**
 * Migration-source selector used to produce the migration items. Pass the same value to
 * detection and import; missing or unrecognized values use the default source.
 */
migrationSource?: string | null, };
