// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FeedbackUploadResponse = { threadId: string,
/**
 * Whitespace-normalized SHA-256 of the session base instructions, matching the
 * uploaded `prompt_hash` tag. Does not include later developer messages.
 * Null when the reported rollout has no prompt metadata.
 */
promptHash: string | null, };
