// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GatewayOAuthStatus } from "./GatewayOAuthStatus";

/**
 * Current effective gateway policy and credential readiness; never contains credentials.
 */
export type GatewayOAuthReadResponse = { providerId: string, providerName: string,
/**
 * Whether the selected provider uses gateway OAuth, even when already signed in.
 */
required: boolean,
/**
 * Null when the effective provider does not use gateway OAuth.
 */
status: GatewayOAuthStatus | null, error: string | null, };
