// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GatewayOAuthStatus } from "./GatewayOAuthStatus";

export type GatewayOAuthChangedNotification = {
/**
 * Authorization handoff, sent only to the connection that started login.
 */
authUrl: string | null, providerId: string, status: GatewayOAuthStatus, error: string | null, };
