// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Usage-read capabilities of the requesting client, never inferred from its experiment arm.
 */
export type GetAccountRateLimitsParams = {
/**
 * The client supports automatic Luna Reserve fallback. For eligible ChatGPT CLI users,
 * allow the backend to record experiment exposure after ordinary usage is blocked.
 */
supportsLunaReserve?: boolean,
/**
 * Skip the separate reset-credit detail lookup for background usage polls. The usage
 * response still includes the available count; omitted/false preserves detailed reads.
 */
excludeResetCreditDetails?: boolean, };
