// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetAccountTokenUsageParams = {
/**
 * When present, read estimated usage for this thread instead of account-wide token activity.
 */
threadId?: string | null, };
