// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceMessage } from "./WorkspaceMessage";

export type GetWorkspaceMessagesResponse = {
/**
 * Whether the workspace-message backend route is available for this client.
 */
featureEnabled: boolean,
/**
 * Active workspace messages returned by the backend.
 */
messages: Array<WorkspaceMessage>, };
