// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Installed connector runtime state.
 */
export type InstalledApp = { id: string,
/**
 * Best-effort name carried by the runtime tool catalog. Canonical app metadata remains owned
 * by `app/read`.
 */
runtimeName: string | null,
/**
 * Effective enabled state after applying global, workspace, local, and managed configuration
 * at read time.
 */
enabled: boolean,
/**
 * Whether the connector is enabled and has a non-synthetic, model-visible tool allowed by
 * effective MCP and app/tool policy in the committed runtime snapshot.
 */
callable: boolean, };
