// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpResourceReadTarget = { connectorId: string,
/**
 * Null explicitly requests no-auth access, subject to the app's resource policy.
 */
linkId: string | null, };
