// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpResourceReadTarget } from "./McpResourceReadTarget";

export type McpResourceReadParams = { threadId?: string | null,
/**
 * Originating MCP tool call used to select the resource's app.
 */
originCallId?: string | null, server: string, uri: string, connectorId?: string | null,
/**
 * Explicit hosted app/account. Omit to retain legacy resource discovery.
 */
target?: McpResourceReadTarget | null, };
