// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpServerOauthLoginCompletedNotification = { name: string, threadId: string | null,
/**
 * Identifies the explicit login attempt. Older servers omit this field.
 */
loginId?: string | null, success: boolean, error?: string, };
