// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerOauthClientRegistration } from "./McpServerOauthClientRegistration";

export type McpServerOauthLoginParams = { name: string, threadId?: string | null,
/**
 * Registration strategy for this login only; omission selects automatic discovery.
 */
clientRegistration?: McpServerOauthClientRegistration | null, scopes?: Array<string> | null, timeoutSecs?: bigint | null, };
