// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CyberAccessProgram } from "./CyberAccessProgram";

/**
 * Caller-specific explicit access programs advertised by model discovery.
 */
export type ModelAccessPrograms = {
/**
 * Accepted explicit selections.
 */
cyber: Array<CyberAccessProgram>, };
