// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginIcon = { src: string, mimeType: string | null, sizes: Array<string> | null, theme: string | null, };
