// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginIcon } from "./PluginIcon";
import type { PluginQuickAction } from "./PluginQuickAction";

export type PluginEntrypoint = { "type": "global", quickAction: PluginQuickAction | null, appId: string, toolName: string, title: string, resourceUri: string, icons: Array<PluginIcon>, } | { "type": "settings", searchTerms: Array<string>, appId: string, toolName: string, title: string, resourceUri: string, icons: Array<PluginIcon>, } | { "type": "thread", appId: string, toolName: string, title: string, resourceUri: string, icons: Array<PluginIcon>, } | { "type": "file", extensions: Array<string>, appId: string, toolName: string, title: string, resourceUri: string, icons: Array<PluginIcon>, };
