// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginIcon } from "./PluginIcon";
import type { PluginQuickActionTarget } from "./PluginQuickActionTarget";

export type PluginQuickAction = { title: string, icons: Array<PluginIcon>, target: PluginQuickActionTarget, };
