// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginAuthPolicy } from "./PluginAuthPolicy";
import type { PluginAvailability } from "./PluginAvailability";
import type { PluginDisabledReason } from "./PluginDisabledReason";
import type { PluginInstallPolicy } from "./PluginInstallPolicy";
import type { PluginInstallPolicySource } from "./PluginInstallPolicySource";
import type { PluginInterface } from "./PluginInterface";
import type { PluginShareContext } from "./PluginShareContext";
import type { PluginSource } from "./PluginSource";

export type PluginSummary = { id: string,
/**
 * Backend remote plugin identifier when available.
 */
remotePluginId: string | null,
/**
 * Version advertised by the remote marketplace backend when available.
 */
version: string | null,
/**
 * Version of the locally materialized plugin package when available.
 */
localVersion: string | null, name: string,
/**
 * Remote sharing context associated with this plugin when available.
 */
shareContext: PluginShareContext | null, source: PluginSource, installed: boolean,
/**
 * Unix timestamp in seconds when the remote plugin was installed, when available.
 */
installedAt: number | null, enabled: boolean, installPolicy: PluginInstallPolicy, installPolicySource: PluginInstallPolicySource | null, mustShowInstallationInterstitial: boolean | null, authPolicy: PluginAuthPolicy,
/**
 * Availability state for installing and using the plugin.
 */
availability: PluginAvailability,
/**
 * Why the remote plugin is unavailable, when provided by plugin-service.
 */
disabledReason: PluginDisabledReason | null,
/**
 * Raw plugin-service plan identifiers eligible to install the plugin.
 */
eligiblePlanTypes: Array<string> | null, interface: PluginInterface | null, keywords: Array<string>, };
