// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginSearchProviderCall } from "./PluginSearchProviderCall";

export type PluginSearchProvider = { appId: string, toolName: string, linkId: string, title: string, call: PluginSearchProviderCall | null, };
