// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginEntrypoint } from "./PluginEntrypoint";
import type { PluginSearchProvider } from "./PluginSearchProvider";
import type { PluginSettings } from "./PluginSettings";

export type PluginExtensions = { entrypoints: Array<PluginEntrypoint> | null, settingsEntrypoints: Array<PluginEntrypoint>, settings: Array<PluginSettings>, threadEntrypoints: Array<PluginEntrypoint>, fileHandlers: Array<PluginEntrypoint>, searchMentionProviders: Array<PluginSearchProvider>, };
