// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PTY size in character cells for `process/spawn` PTY sessions.
 */
export type ProcessTerminalSize = {
/**
 * Terminal height in character cells.
 */
rows: number,
/**
 * Terminal width in character cells.
 */
cols: number, };
