// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StrictReviewRequiredNotification = { threadId: string, turnId: string,
/**
 * Unix timestamp (in milliseconds) when this review started.
 */
startedAtMs: number, };
