// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadAttachment } from "./ThreadAttachment";
import type { ThreadAttachmentAddOutcome } from "./ThreadAttachmentAddOutcome";

/**
 * The created or existing attachment.
 */
export type ThreadAttachmentAddResponse = { outcome: ThreadAttachmentAddOutcome, attachment: ThreadAttachment, };
