// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadRealtimeItem } from "./ThreadRealtimeItem";

/**
 * EXPERIMENTAL - a realtime timeline item published after canonical commit.
 */
export type ThreadRealtimeItemCompletedNotification = { threadId: string, item: ThreadRealtimeItem, };
