// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Thread } from "./Thread";

export type ThreadRevertResponse = {
/**
 * Updated loaded thread metadata. `turns` is always empty; hydrate retained history through
 * `thread/turns/list`.
 */
thread: Thread,
/**
 * Opaque cursor for hydrating paginated turns backwards.
 *
 * Pass this as `cursor` to `thread/turns/list` with
 * `sortDirection: "desc"`. The first page includes the turn identified by the cursor.
 */
turnsBackwardsCursor: string | null,
/**
 * Opaque cursor for hydrating paginated items backwards.
 *
 * Pass this as `cursor` to `thread/items/list` with
 * `sortDirection: "desc"`. The first page includes the item identified by the cursor.
 */
itemsBackwardsCursor: string | null, };
