// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSection } from "./ThreadSection";

/**
 * The independently persisted section after its name is updated.
 */
export type ThreadSectionUpdateResponse = { section: ThreadSection, };
