// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadItemEntry } from "./ThreadItemEntry";

export type ThreadItemsListResponse = { data: Array<ThreadItemEntry>,
/**
 * Opaque cursor to pass to the next call to continue after the last item.
 * if None, there are no more items to return.
 */
nextCursor: string | null,
/**
 * Opaque cursor to pass as `cursor` when reversing `sortDirection`.
 * This is only populated when the page contains at least one item.
 */
backwardsCursor: string | null, };
