// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for moving a thread within a server-owned section ordering.
 */
export type ThreadSectionMoveParams = {
/**
 * Thread to move into, within, or out of a section.
 */
threadId: string,
/**
 * Destination section, or `null` to remove the thread from its section.
 */
sectionId: string | null,
/**
 * Existing thread to insert before; omission or null appends to the section.
 */
beforeThreadId?: string | null, };
