// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationTextRole } from "../ConversationTextRole";

/**
 * EXPERIMENTAL - role-bearing text item included when a realtime V3 session starts.
 */
export type ThreadRealtimeInitialItem = { role: ConversationTextRole, text: string, };
