// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of attempting to associate an attachment with a thread.
 */
export type ThreadAttachmentAddOutcome = "created" | "existing";
