// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for deleting an independently persisted thread section.
 */
export type ThreadSectionDeleteParams = {
/**
 * The stable, server-generated identity of the section to delete.
 */
sectionId: string, };
