// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Distinguishes explicit user actions from automatic goal lifecycle mutations.
 */
export type ThreadGoalMutationOrigin = "user" | "automatic";
