// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Successful deletion does not return additional section data.
 */
export type ThreadSectionDeleteResponse = Record<string, never>;
