// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSectionAppearance } from "./ThreadSectionAppearance";

/**
 * Parameters for creating an independently persisted thread section.
 */
export type ThreadSectionCreateParams = {
/**
 * The user-visible name of the section.
 */
name: string, appearance?: ThreadSectionAppearance | null, };
