// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The persisted attachment change represented by a notification.
 */
export type ThreadAttachmentOperation = "created" | "deleted";
