// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSection } from "./ThreadSection";

/**
 * One page of independently persisted thread sections.
 */
export type ThreadSectionListResponse = { data: Array<ThreadSection>,
/**
 * Opaque cursor for the next page, or `null` when no sections remain.
 */
nextCursor: string | null, };
