// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadAttachment } from "./ThreadAttachment";

/**
 * One page of attachments associated with the requested thread.
 */
export type ThreadAttachmentListResponse = { data: Array<ThreadAttachment>, nextCursor: string | null, };
