// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadGoalMutationOrigin } from "./ThreadGoalMutationOrigin";

export type ThreadGoalClearParams = { threadId: string,
/**
 * Missing provenance does not supply user authorization.
 */
origin?: ThreadGoalMutationOrigin | null, };
