// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for deleting an attachment by its stable thread-local identity.
 */
export type ThreadAttachmentRemoveParams = { threadId: string, attachmentType: string, identityKey: string, };
