// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortDirection } from "./SortDirection";
import type { ThreadItemsListCursor } from "./ThreadItemsListCursor";

export type ThreadItemsListParams = { threadId: string,
/**
 * Optional turn id to filter by. When omitted, returns items across the thread.
 */
turnId?: string | null,
/**
 * Opaque continuation cursor or an exclusive item anchor in the requested visible turn.
 * An item anchor requires a non-empty `turnId`; ascending (the default) returns items
 * after it, and descending returns items before it. Continue with the returned string cursor.
 */
cursor?: ThreadItemsListCursor | null,
/**
 * Optional item page size.
 */
limit?: number | null,
/**
 * Optional item pagination direction; defaults to ascending.
 */
sortDirection?: SortDirection | null, };
