// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceMessageType } from "./WorkspaceMessageType";

export type WorkspaceMessage = { messageId: string, messageType: WorkspaceMessageType, messageBody: string,
/**
 * Unix timestamp (in seconds) when the message was created.
 */
createdAt: number | null,
/**
 * Unix timestamp (in seconds) when the message was archived.
 */
archivedAt: number | null, };
