// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A model-facing surface on which a tool can be exposed.
 */
export type ToolExposureSurface = "code_mode" | "deferred" | "direct";
